// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_JFByqlCyojA76X0odlT-nWnW5eTSW0s',
    appId: '1:832544989118:web:56a4a2ab798b010bae63ef',
    messagingSenderId: '832544989118',
    projectId: 'femn-9cabb',
    authDomain: 'femn-9cabb.firebaseapp.com',
    storageBucket: 'femn-9cabb.firebasestorage.app',
    measurementId: 'G-ZSZZYYEZGB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAH-t2jr5YJYqF-yH1ONdbr0MLucrBb-DI',
    appId: '1:832544989118:android:313ad83b4e753868ae63ef',
    messagingSenderId: '832544989118',
    projectId: 'femn-9cabb',
    storageBucket: 'femn-9cabb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDV3ZdVsPpg1TIFP9xLymXPlaXqbWFE9XQ',
    appId: '1:832544989118:ios:7623a889e9bd5b61ae63ef',
    messagingSenderId: '832544989118',
    projectId: 'femn-9cabb',
    storageBucket: 'femn-9cabb.firebasestorage.app',
    iosBundleId: 'com.example.femn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDV3ZdVsPpg1TIFP9xLymXPlaXqbWFE9XQ',
    appId: '1:832544989118:ios:7623a889e9bd5b61ae63ef',
    messagingSenderId: '832544989118',
    projectId: 'femn-9cabb',
    storageBucket: 'femn-9cabb.firebasestorage.app',
    iosBundleId: 'com.example.femn',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_JFByqlCyojA76X0odlT-nWnW5eTSW0s',
    appId: '1:832544989118:web:b583564fe254bf09ae63ef',
    messagingSenderId: '832544989118',
    projectId: 'femn-9cabb',
    authDomain: 'femn-9cabb.firebaseapp.com',
    storageBucket: 'femn-9cabb.firebasestorage.app',
    measurementId: 'G-HJJP1BWG8T',
  );
}
